langchain4j:
  open-ai:
    chat-model:
      base-url:
      api-key:
      model-name:
      log-responses: true
      log-requests: true
    streaming-chat-model:
      base-url:
      api-key:
      model-name:
      log-responses: true
      log-requests: true

logging:
  level:
    dev.langchain4j: debug
    com.example.kui: info
